controller_routing:
    resource: "@YosimitsoWorkingForumBundle/Controller/*"
    type: annotation

workingforum_admin:
    path: /admin
    defaults: { _controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminController:indexAction }

workingforum_admin_forum_edit:
    path: /admin/forum/edit/{id}
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController:editAction }
    requirements:
        id: '\d+'

workingforum_admin_forum_add:
    path: /admin/forum/add
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController:addAction }

workingforum_admin_delete_forum:
    path: /admin/forum/delete/{forum_id}
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminForumController:deleteForumAction }
    requirements:
        forum_id: '\d+'

workingforum_admin_forum_rules:
    path: /admin/rules
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController:rulesAction }

workingforum_admin_edit_forum_rules:
    path: /admin/rules/edit/{lang}
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController:rulesEditAction }

workingforum_admin_new_forum_rules:
    path: /admin/rules/new/{lang}
    defaults:
          _controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminRulesController:rulesNewAction
          newLang: true

workingforum_admin_install_settings:
    path: /admin/install-settings
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminController:installSettingsAction }

workingforum_admin_report:
    path: /admin/report
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController:reportAction }

workingforum_admin_report_history:
    path: /admin/report/history
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController:reportHistoryAction }

workingforum_admin_report_action_moderate:
    path: /admin/reportaction/moderate
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController:reportActionModerateAction }

workingforum_admin_report_action_good:
    path: /admin/reportaction/good
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminReportController:reportActionGoodAction }

workingforum_admin_user:
    path: /admin/users
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\Admin\AdminUsersController:userListAction }

workingforum_search:
    path: /search
    defaults: {_controller: Yosimitso\WorkingForumBundle\Controller\SearchController:indexAction }

workingforum_vote_up:
    path: /voteup
    defaults: { _controller: Yosimitso\WorkingForumBundle\Controller\PostController:voteUpAction }
